name: Deploy to Netlify

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Choose the right version for your project

      - name: Install dependencies
        run: npm install

      - name: Create Netlify _redirects file
        run: |
          echo "/*    /index.html   200" > ./public/_redirects

      - name: Build the project
        run: npm run build

      - name: Copy _redirects file to dist
        run: cp ./public/_redirects ./dist/_redirects

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './dist'  # Output directory of Vite's build command
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
